//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace backEnd.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class aboutTbl
    {
        public int about_id { get; set; }
        public string body { get; set; }
        public string mapLink { get; set; }
        public string emial { get; set; }
        public string officeAddress { get; set; }
        public string phoneNumber1 { get; set; }
        public string phoneNumber2 { get; set; }
    }
}
