//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace backEnd.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class banner_tbl
    {
        public int banner_id { get; set; }
        public string banner_title { get; set; }
        public string link { get; set; }
        public string images { get; set; }
        public Nullable<int> sort_order { get; set; }
    }
}
