//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace backEnd.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class customer_tbl
    {
        public int customer_id { get; set; }
        public string firstname { get; set; }
        public string lastname { get; set; }
        public string email { get; set; }
        public string gender { get; set; }
        public string telephone { get; set; }
        public Nullable<int> address_id { get; set; }
        public string ip { get; set; }
        public Nullable<bool> newsletter { get; set; }
        public Nullable<bool> status { get; set; }
        public string token { get; set; }
        public string code { get; set; }
        public Nullable<int> approved { get; set; }
        public Nullable<System.DateTime> date_added { get; set; }
        public string aspnetuserid { get; set; }
    }
}
