//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace backEnd.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class item_ladger
    {
        public int ladger_id { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public Nullable<int> wareHouse_ID { get; set; }
        public string Invoies { get; set; }
        public Nullable<int> pIn { get; set; }
        public Nullable<int> pOut { get; set; }
        public Nullable<int> pBlance { get; set; }
        public Nullable<int> status { get; set; }
        public Nullable<int> proID { get; set; }
    }
}
