//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace backEnd.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class order_total_tbl
    {
        public int order_total_id { get; set; }
        public Nullable<int> order_id { get; set; }
        public string code { get; set; }
        public string title { get; set; }
        public Nullable<decimal> value { get; set; }
        public Nullable<int> sort_order { get; set; }
    }
}
