//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace backEnd.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class order_tbl
    {
        public int order_id { get; set; }
        public Nullable<int> invoice_no { get; set; }
        public string invoice_prefix { get; set; }
        public Nullable<int> customer_id { get; set; }
        public string firstname { get; set; }
        public string lastname { get; set; }
        public string email { get; set; }
        public string telephone { get; set; }
        public string payment_firstname { get; set; }
        public string payment_lastname { get; set; }
        public string payment_telephone { get; set; }
        public string payment_address_1 { get; set; }
        public string payment_address_2 { get; set; }
        public string payment_district { get; set; }
        public string payment_thana { get; set; }
        public string payment_postcode { get; set; }
        public string payment_country { get; set; }
        public string payment_method { get; set; }
        public string shipping_firstname { get; set; }
        public string shipping_lastname { get; set; }
        public string shipping_telephone { get; set; }
        public string shipping_address_1 { get; set; }
        public string shipping_address_2 { get; set; }
        public string shipping_district { get; set; }
        public string shipping_thana { get; set; }
        public string shipping_postcode { get; set; }
        public string shipping_country { get; set; }
        public string shipping_method { get; set; }
        public string comment { get; set; }
        public Nullable<decimal> total { get; set; }
        public string tracking { get; set; }
        public string order_status { get; set; }
        public string ip { get; set; }
        public string user_agent { get; set; }
        public Nullable<System.DateTime> date_added { get; set; }
        public Nullable<System.DateTime> date_modified { get; set; }
        public Nullable<int> WareHouseID { get; set; }
        public Nullable<decimal> amont { get; set; }
        public Nullable<decimal> totalSave { get; set; }
    }
}
