//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace backEnd.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class order_history_tbl
    {
        public int order_history_id { get; set; }
        public Nullable<int> order_id { get; set; }
        public string order_status { get; set; }
        public Nullable<bool> notify { get; set; }
        public string comment { get; set; }
        public Nullable<System.DateTime> date_added { get; set; }
        public string user_id { get; set; }
    }
}
