//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace backEnd.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class product_tbl
    {
        public int product_id { get; set; }
        public string p_name { get; set; }
        public Nullable<double> quantity { get; set; }
        public Nullable<int> stock_status_id { get; set; }
        public string main_image { get; set; }
        public Nullable<int> manufacturer_id { get; set; }
        public Nullable<decimal> price { get; set; }
        public Nullable<int> points { get; set; }
        public Nullable<System.DateTime> date_available { get; set; }
        public Nullable<int> status { get; set; }
        public Nullable<int> viewed { get; set; }
        public Nullable<System.DateTime> date_added { get; set; }
        public Nullable<System.DateTime> date_modified { get; set; }
        public string discription { get; set; }
        public string tag { get; set; }
        public string meta_title { get; set; }
        public string meta_description { get; set; }
        public string meta_keyword { get; set; }
        public string Entry_by { get; set; }
        public Nullable<int> sort_order { get; set; }
        public string VideoLink { get; set; }
    }
}
