//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace backEnd.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class product_variant_unit_VT
    {
        public int id { get; set; }
        public Nullable<int> Variant_id { get; set; }
        public Nullable<int> product_id { get; set; }
        public Nullable<int> value { get; set; }
        public Nullable<int> variant_unit { get; set; }
        public int varient_id { get; set; }
        public string varient_name { get; set; }
        public int variant_unit_id { get; set; }
        public string unit_name { get; set; }
        public Nullable<int> Expr1 { get; set; }
    }
}
