//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace backEnd.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class product_review_id
    {
        public int review_id { get; set; }
        public Nullable<int> product_id { get; set; }
        public Nullable<int> customer_id { get; set; }
        public string author { get; set; }
        public string text { get; set; }
        public Nullable<int> rating { get; set; }
        public Nullable<int> status { get; set; }
        public Nullable<System.DateTime> date_added { get; set; }
        public Nullable<System.DateTime> date_modified { get; set; }
    }
}
