//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace backEnd.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductViewTable
    {
        public int product_id { get; set; }
        public string p_name { get; set; }
        public Nullable<double> quantity { get; set; }
        public Nullable<int> stock_status_id { get; set; }
        public string main_image { get; set; }
        public Nullable<int> manufacturer_id { get; set; }
        public Nullable<decimal> price { get; set; }
        public Nullable<int> points { get; set; }
        public Nullable<System.DateTime> date_available { get; set; }
        public Nullable<int> status { get; set; }
        public Nullable<int> viewed { get; set; }
        public Nullable<System.DateTime> date_added { get; set; }
        public Nullable<System.DateTime> date_modified { get; set; }
        public string discription { get; set; }
        public string tag { get; set; }
        public string meta_title { get; set; }
        public string meta_description { get; set; }
        public string meta_keyword { get; set; }
        public string Entry_by { get; set; }
        public Nullable<int> sort_order { get; set; }
        public Nullable<int> sl { get; set; }
        public Nullable<int> Expr1 { get; set; }
        public Nullable<int> category_id { get; set; }
        public Nullable<int> id { get; set; }
        public Nullable<int> Variant_id { get; set; }
        public Nullable<int> Expr2 { get; set; }
        public Nullable<int> value { get; set; }
        public Nullable<int> variant_unit { get; set; }
        public Nullable<int> product_image_id { get; set; }
        public Nullable<int> Expr3 { get; set; }
        public string image { get; set; }
        public Nullable<int> Expr4 { get; set; }
        public Nullable<int> Expr6 { get; set; }
        public Nullable<int> Expr5 { get; set; }
        public Nullable<int> releted_product_ID { get; set; }
    }
}
