//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace backEnd.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class product_supplier
    {
        public int product_supplier_id { get; set; }
        public Nullable<int> product_id { get; set; }
        public Nullable<int> supplier_id { get; set; }
    }
}
