//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace backEnd.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class purchase
    {
        public int purchase_id { get; set; }
        public Nullable<int> supplier_id { get; set; }
        public Nullable<decimal> total_amount { get; set; }
        public Nullable<int> warehouse_id { get; set; }
        public Nullable<System.DateTime> create_date { get; set; }
        public string pInv { get; set; }
    }
}
