//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace backEnd.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class site_setting_tbl
    {
        public int id { get; set; }
        public string siteName { get; set; }
        public string cName { get; set; }
        public string logo { get; set; }
        public string About { get; set; }
        public Nullable<int> Invoic { get; set; }
    }
}
