//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace backEnd.DataModel
{
    using System;
    using System.Collections.Generic;
    using System.Web;

    public partial class slider_image_tbl
    {
        public int slider_image_id { get; set; }
        public Nullable<int> slider_id { get; set; }
        public string title { get; set; }
        public string subtitle { get; set; }
        public string link { get; set; }
        public string image { get; set; }
        public Nullable<int> sort_order { get; set; }

        public HttpPostedFileBase banner { get; set; }
    }
}
