//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace backEnd.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class social_site
    {
        public int socialId { get; set; }
        public string fb { get; set; }
        public string tw { get; set; }
        public string ig { get; set; }
        public string gp { get; set; }
        public string pt { get; set; }
    }
}
