//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace abcShop.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class coupon_history_tbl
    {
        public int coupon_history_id { get; set; }
        public Nullable<int> coupon_id { get; set; }
        public Nullable<int> order_id { get; set; }
        public Nullable<int> customer_id { get; set; }
        public Nullable<decimal> amount { get; set; }
        public Nullable<System.DateTime> date_added { get; set; }
    }
}
