//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace abcShop.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class coupon_tbl
    {
        public int coupon_id { get; set; }
        public string name { get; set; }
        public string code { get; set; }
        public Nullable<int> type { get; set; }
        public Nullable<decimal> discount { get; set; }
        public Nullable<int> logged { get; set; }
        public Nullable<int> shipping { get; set; }
        public Nullable<decimal> total { get; set; }
        public Nullable<System.DateTime> date_start { get; set; }
        public Nullable<System.DateTime> date_end { get; set; }
        public Nullable<int> uses_total { get; set; }
        public string uses_customer { get; set; }
        public Nullable<int> status { get; set; }
        public Nullable<System.DateTime> date_added { get; set; }
    }
}
