//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace abcShop.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class manufacturer_tbl
    {
        public int manufacturer_id { get; set; }
        public string brand_name { get; set; }
        public string logo { get; set; }
        public Nullable<int> sort_order { get; set; }
    }
}
