//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace abcShop.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class product_variant_value
    {
        public int pvvID { get; set; }
        public Nullable<int> pv_Id { get; set; }
        public Nullable<int> product_id { get; set; }
        public Nullable<int> price { get; set; }
        public Nullable<int> variant_unit_id { get; set; }
        public string variant_unit_name { get; set; }
        public Nullable<int> variant_id { get; set; }
        public string variant_name { get; set; }
        public Nullable<int> quentity { get; set; }
    }
}
