//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace abcShop.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class site_option_tbl
    {
        public int site_option_id { get; set; }
        public string logo { get; set; }
        public string mobile { get; set; }
        public string address { get; set; }
        public string google_map { get; set; }
        public string email { get; set; }
        public string schedule { get; set; }
    }
}
