//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace abcShop.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class userCart_tbl
    {
        public int CartID { get; set; }
        public Nullable<int> product_ID { get; set; }
        public string productName { get; set; }
        public Nullable<decimal> mainPrice { get; set; }
        public Nullable<decimal> varintPrice { get; set; }
        public Nullable<decimal> totalPrice { get; set; }
        public Nullable<int> Quantity { get; set; }
        public string pvvalueID { get; set; }
        public string VarintName { get; set; }
        public string userID { get; set; }
        public string sessionID { get; set; }
        public string varintUnit { get; set; }
        public string img { get; set; }
        public Nullable<decimal> discountPrice { get; set; }
    }
}
